### ISSUE TITLE
Update Python API examples with accurate usage messages

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#1]
originally here: https://github.com/zulip/zulip/issues/3365

from dehnert:

The Python API examples use generate_option_group and init_from_options to support a common set of options, but (mostly?) hardcode their usage messages. They should ideally display a more complete usage message as well (or instead) that reflects the other options, especially --config-file (though others are also occasionally useful, certainly).

**Comment by dehnert** [comment]
AFAICT, this works now?
```
$ examples/print-messages -h
Usage: print-messages --user=<bot's email address> --api-key=<bot's api key> [options]

Prints out each message received by the indicated bot or user.

Example: print-messages --user=username@example.com --api-key=a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5

You can omit --user and --api-key arguments if you have a properly set up ~/.zuliprc


Options:
  -h, --help            show this help message and exit

  Zulip API configuration:
    --site=ZULIP_SITE   Zulip server URI
    --api-key=ZULIP_API_KEY
    --user=ZULIP_EMAIL  Email address of the calling bot or user.
    --config-file=ZULIP_CONFIG_FILE
                        Location of an ini file containing the above
                        information. (default ~/.zuliprc)
    -v, --verbose       Provide detailed output.
    --insecure          Do not verify the server certificate.
                        The https connection will not be secure.
    --cert-bundle=CERT_BUNDLE
                        Specify a file containing either the
                        server certificate, or a set of trusted
                        CA certificates. This will be used to
                        verify the server's identity. All
                        certificates should be PEM encoded.
    --client-cert=CLIENT_CERT
                        Specify a file containing a client
                        certificate (not needed for most deployments).
    --client-cert-key=CLIENT_CERT_KEY
                        Specify a file containing the client
                        certificate's key (if it is in a separate
                        file).
```

I'm a little confused, because I can't seem to find a code change that *made* this work. It's possible that I was just going off the code or something, but I think I actually got confused when running it?

Maybe I was specifically complaining about the first line, with the actual usage example. I don't think that's a big deal as long as `--config-file` and so forth get listed below.

**Comment by dehnert** [comment]
Okay, maybe my source of confusion was that if you try an unknown option, you get the usage message (which is misleading) but it's not immediately obvious that `--help` will be more informative. Unfortunately, it doesn't appear that you can add prefatory text to `--help` output using `optparse` without also also having it appear when an unknown option is passed.

I wonder if the right way to format the usage messages is to base them on the assumption that `~/.zuliprc` will exist, and just do `send-message [options] recipients` or similar. The"`You can omit --user and --api-key arguments if you have a properly set up ~/.zuliprc" line might be better as something like "If you do not have a zuliprc set up, you can pass the site, user, and API key on the command line or in the environment. See documentation for details." or something.

**Comment by timabbott** [comment]
Since we're migrating to argparse, this situation may change in terms of what's easy to do...

**Comment by timabbott** [comment]
OK, so I think there are 2 parts to resolving this:
(1) Removing the hardcoding of `--user` and `--api-key` in the `usage` of our various API examples, since we expect users to use a `.zuliprc` file.  I've done `zulip/examples/send_message` here: 5bc98bfdf76e9d4964f2667fa94b5c06869b2e40.  Someone else can take up the rest of this.

(2) Making `./zulip/examples/send-message --foo` recommend `--help`, rather than just showing the top part of `usage` text (which doesn't explain what options do work, and thus requires that the user know that `--help` is the magic option for getting help).  May require some figuring out.  Let's split this to a separate issue.
