### ISSUE TITLE
Potential code quality issues found

### ISSUE THREAD

**Issue by pnijhara** [zulip/python-zulip-api#607]
I have forked this [repo](https://github.com/pnijhara/python-zulip-api/tree/pnijhara-patch-1) and later to check code quality, I ran a [DeepSource](https://deepsource.io) analysis on it. There I found around 700+ code quality issues, some of them can be easily fixed in a single click.

Those issues are categorized as:

Anti-pattern: 425 
Bug Risk: 49
Performance: 188
Security: 57

Find a detailed report of the issues found here -> https://deepsource.io/gh/pnijhara/python-zulip-api/issues/?category=recommended

I have also added a deepsource config file to let DeepSource analyze my forked repo. The link of that file can be found [here](https://github.com/pnijhara/python-zulip-api/blob/pnijhara-patch-1/.deepsource.toml).

I want to send a patch with some fix.

Also do let me know which of the above issues you think are false positives and which of them are potential issues.

**Comment by timabbott** [comment]
We love taking patches that improve the codebase, and use other code scanners to look for them.  

Based on past experience, I'd be surprised if many of those "700 issues" are real problems -- this class of tool is known for generating a lot of spam because it helps sell that class of software.  And 188 "performance" issues in a small codebase like this API library is a sign that they're very aggressive about flagging things.
