### ISSUE TITLE
bots: Audit bots for filesystem access.

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#9]
see https://github.com/zulip/zulip/issues/5395 for context

We want to double check that:
* bots use StateHandler for saving state
* bots don't directly access the file system for config info

This project may already be done, and the best person to address this issue is somebody fairly involved with the project already, so they know what to check for.

**Comment by derAnfaenger** [comment]
Sorry for this late reply!
@tabbott this is partially done, except for the part where we want to handle general file accesses by bots. I've started to write up a PR for this, but got heavily delayed due to my Asia trip. Assuming this is nothing critical, I'll be happy to say that I'm still working on this.

**Comment by tabbott** [comment]
thanks for the update :q

**Comment by derAnfaenger** [comment]
Oh no, now I'm already tagging the wrong people :/ sorry, meant @timabbott

**Comment by tabbott** [comment]
No worries! It's actually not the first time this has happened. Perhaps not the last time either :)

**Comment by timabbott** [comment]
OK that plan makes sense @derAnfaenger.

**Comment by derAnfaenger** [comment]
@timabbott this issue can be closed.

**Comment by timabbott** [comment]
Sounds good!
